# Generated by Django 4.1 on 2022-08-08 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='desc',
            field=models.TextField(default='', max_length=400),
            preserve_default=False,
        ),
    ]
