# Generated by Django 4.1 on 2022-08-10 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_mainvideo_alter_photo_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainCarousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='imgs/main_carousel/')),
            ],
        ),
    ]
