# Generated by Django 4.1 on 2022-08-10 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_snapshot_delete_snapphotos_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commercialproject',
            options={'verbose_name': 'Commercial Project'},
        ),
        migrations.AlterModelOptions(
            name='maincarousel',
            options={'verbose_name': 'Carousel'},
        ),
        migrations.AlterModelOptions(
            name='personalproject',
            options={'verbose_name': 'Personal Project'},
        ),
        migrations.AlterModelOptions(
            name='snapshot',
            options={'verbose_name': 'Snapshot'},
        ),
        migrations.AlterField(
            model_name='commercialphotos',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='imgs/commercial/<django.db.models.query_utils.DeferredAttribute object at 0x000002B34D527AC0>/'),
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='title',
            field=models.CharField(default='snapIXu0Ylns', max_length=200),
        ),
    ]
