# Generated by Django 4.1 on 2022-08-10 23:57

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_commercialproject_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commercialproject',
            options={'verbose_name': 'Commercial Project', 'verbose_name_plural': 'Commercial Project'},
        ),
        migrations.AlterModelOptions(
            name='maincarousel',
            options={'verbose_name': 'Carousel', 'verbose_name_plural': 'Carousel'},
        ),
        migrations.AlterModelOptions(
            name='mainvideo',
            options={'verbose_name': 'Main Video', 'verbose_name_plural': 'Main Video'},
        ),
        migrations.AlterModelOptions(
            name='personalproject',
            options={'verbose_name': 'Personal Project', 'verbose_name_plural': 'Personal Project'},
        ),
        migrations.AlterModelOptions(
            name='snapshot',
            options={'verbose_name': 'Snapshot', 'verbose_name_plural': 'Snapshot'},
        ),
        migrations.AlterField(
            model_name='commercialphotos',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='imgs/commercial/<django.db.models.query_utils.DeferredAttribute object at 0x0000024A3AE99BD0>/'),
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='title',
            field=models.CharField(default=main.models.generate_id, max_length=200),
        ),
    ]
