# Generated by Django 4.1 on 2022-08-11 05:01

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_commercialproject_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commercialphotos',
            options={'verbose_name': 'Commercial Project Photos', 'verbose_name_plural': 'Commercial Project Photo'},
        ),
        migrations.AlterModelOptions(
            name='personalphotos',
            options={'verbose_name': 'Personal Project Photos', 'verbose_name_plural': 'Personal Project Photo'},
        ),
        migrations.AddField(
            model_name='personalproject',
            name='serial',
            field=models.CharField(default=main.models.generate_id, max_length=50),
        ),
        migrations.AlterField(
            model_name='commercialphotos',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='imgs/commercial/<django.db.models.query_utils.DeferredAttribute object at 0x00000210877B9BD0>/'),
        ),
    ]
