# Generated by Django 4.1 on 2022-08-11 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_commercialphotos_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercialphotos',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='imgs/commercial/<django.db.models.query_utils.DeferredAttribute object at 0x000002445BF19BD0>/'),
        ),
    ]
