# Generated by Django 4.1 on 2022-08-12 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_commercialphotos_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercialphotos',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='imgs/commercial'),
        ),
        migrations.AlterField(
            model_name='personalphotos',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='imgs/project'),
        ),
    ]
