# Generated by Django 4.1 on 2022-08-12 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_commercialphotos_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercialphotos',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commercial_project', to='main.commercialproject'),
        ),
        migrations.AlterField(
            model_name='personalphotos',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_project', to='main.personalproject'),
        ),
    ]
