# Generated by Django 4.1 on 2022-09-19 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_maincarousel_background_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercialproject',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='imgs/project'),
        ),
        migrations.AddField(
            model_name='personalproject',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='imgs/project'),
        ),
    ]
