# Generated by Django 4.1 on 2022-09-19 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_commercialproject_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercialproject',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='imgs/commercial'),
        ),
    ]
